import { Icareer } from "../CareerList";
export const apothecary: Icareer = {
    value: "apothecary",
    label: "Apothecary",
    tier: [
        {
            label: "Apothecary’s Apprentice",
            status: ["Brass", 3],
            skills: [
                "consumealcohol",
                "heal",
                ["language", "Classical"],
                ["lore", "Chemistry"],
                ["lore", "Medicine)"],
                ["lore", "Plants"],
                ["trade", "Apothecary"],
                ["trade", "Poisoner"],
            ],
            advances: ["T", "Dex", "Int"],
            talents: [
                "Concoct",
                ["Craftsman", "Apothecary"],
                ["Etiquette", "Scholar"],
                "Read/Write",
            ],
            trappings: [
                "Book (Blank)",
                "Healing Draught",
                "Leather Jerkin",
                "Pestle and Mortar",
            ],
        },
        {
            label: "Apothecary",
            status: ["Silver", 1],
            skills: [
                "charm",
                "haggle",
                ["lore", "Science"],
                "gossip",
                ["language", "Guilder"],
                "perception",
            ],
            advances: ["Fel"],
            talents: [
                "Criminal",
                "Dealmaker",
                ["Etiquette", "Guilder"],
                "Pharmacist",
            ],
            trappings: ["Guild Licence", "Trade Tools"],
        },
        {
            label: "Master Apothecary",
            status: ["Silver", 3],
            skills: [
                "intuition",
                "leadership",
                "research",
                ["secretsigns", "Guilder"],
            ],
            advances: ["I"],
            talents: [
                "Bookish",
                ["Master Tradesman", "Apothecary"],
                ["Resistance", "Poison"],
                "Savvy",
            ],
            trappings: ["Book (Apothecary)", "Apprentice", "Workshop"],
        },
        {
            label: "Apothecary-General",
            status: ["Gold", 1],
            skills: ["intimidate", ["ride", "Horse"]],
            advances: ["WP"],
            talents: [
                ["Acute Sense", "Taste"],
                "Coolheaded",
                ["Master Tradesman", "Poisoner"],
                ["Savant", "Apothecary"],
            ],
            trappings: ["Commission Papers", "Large Workshop"],
        },
    ],
};
